ballot_marking_device() ::= <<
<h2>Ballot Marking Devices (BMD)</h2>

<p><b>Good choice!</b></p>

<p>You are voting with a voting system that was initially designed for the
disabled, as a Ballot Marking Device (BMD) permits physically disabled and
sight-disabled voters to vote independently.  BMDs guarantee that votes are
correctly filled out and print a normal paper ballot.  You then drop the 
ballot into a secure ballot box.</p>

<p>Votes produced with a BMD are either counted by-hand, and thus witness
all of the challenges of hand-marked, hand-counted elections.  Or they are
counted using computers which scan and interpret the paper ballots.  
Try voting with hand-marked ballots or optical scan voting systems
to learn more!</p>

<p>This voting system is a fairly reliable, though complicated, choice.  Its 
operation and security threats are fairly well-understood because people 
have been voting on paper for centuries and most BMDs are simple devices
that record no information about voters whatsoever.</p>

<p>There are a few drawbacks to voting with a BMD.  They are traditionally
fairly expensive, run on old hardware and software that does not see upgrades 
or security patches, and are slow to use.</p>

<p>Another drawback of BMDs is that it is very hard to guarantee that voter 
anonymity and privacy are respected.</p>

<p>On the positive side though, supporting disabled voters is critical for 
fairness in elections in society.  Moreover, all votes will be well-formed and
can be counted, so no voters are accidentally disenfranchised.</p>
>>
