dre() ::= <<
<p><b>Terrible choice!</b></p>

<p>You are voting with a voting system designed in the 20th century,
but unable to withstand the security threats of the 21st century.
</p>

<p>You use an antique computer that no longer gets updates or security patches,
created by a voting company you have never heard of, running a proprietary 
system that no one has ever seriously examined, to collect votes
and announce the election's results.</p>

<p>You have no guarantee of your privacy or anonymity, so the 
authorities could choose to look at how you vote and make your life 
miserable if you didn't vote the "right" way.</p>

<p>Also, if something goes wrong in the election&mdash;perhaps there is a virus
on the DRE that changes the way that you voted without your noticing&mdash;
there is no way for the authorities to detect and mitigate the issue or 
correct the election.</p>

<p>You have put your vote within the reach of sophisticated hackers like state-level adversaries
like Russia, China, and North Korea.</p>

<p>Often there is no paper record of 
your vote.  You have to completely trust the election authorities and 
their technology providers to have any hope that your 
vote is recorded correctly, remains secret, and is counted in the election.</p>

<p>Sometimes there is a paper record in the form of a 
"Voter-Verifiable Paper Audit Trail", or VVPAT for short.  This means that a 
little slip of
paper is printed with your vote on it.  It is behind a piece of dirty glass, 
and is very hard to read and understand.  Voters rarely actually
look at what was printed.</p>

<p>Shockingly, even in close elections, or in elections where something fishy
has happened, election authorities very, very rarely ever look at  
VVPATs!</p>

<p>All voting in Utah and Nevada is on DREs with VVPAT.  Much of the 
voting that happens in California, Idaho, Alaska, Hawaii, Wyoming, Arizona, 
Missouri, Illinois, Wisconsin, Ohio, West Virginia, and North Carolina is on 
DREs with VVPAT. Some of the voting in Kansas, Arkansas, and Mississippi is 
on DREs with VVPAT.</p>

<p> All voting in Louisiana, Georgia, South Carolina, New Jersey, and 
Delaware is on DREs without VVPAT.  Much of the voting that happens in Texas, Florida,
Tennessee, Kentucky, Indiana, Virginia, and Pennsylvania is on DREs without VVPAT.  Good luck
trusting the results of elections in all of these states!</p>

<p><b>Direct-recording electronic voting machines are the <em>worst</em> voting systems in wide 
use in the world today. </b></p>
>>
