dre() ::= <<
<p><b>Terrible choice!</b></p>

<p>You are voting with a voting system designed in the 20th century,
but unable to withstand the security threats of the 21st century.
You have put your election in the hands of state-level adversaries
like Russia, China, and North Korea, or in the hands of untrustworthy
elections officials or other political parties.</p>

<p>You use an antique computer that no longer gets updates or security patches,
created by a voting company you have never heard of, running a proprietary 
system that no one has ever seriously examined, to collect votes
and announce the election's results.</p>

<p>Unfortunately, there is no paper ballot record and no guaranteed receipt of 
your vote.  Also, you have to completely trust the election authorities, 
their technology providers, and your government to have any hope that your 
vote is recorded correctly, remains secret, and is counted in the election.</p>

<p>More worrisome, you have no guarantee of your privacy or anonymity, so the 
authorities could choose to look at how you vote and make your life 
miserable if you didn't vote the "right" way.</p>

<p>Also, if something goes wrong in the election&mdash;perhaps there is a virus
on the DRE that changes the way that you voted without your noticing&mdash;
there is no way for the authorities to detect and mitigate the issue or 
correct the election.</p>

<p>Direct-recording electronic voting machines are the <b>worst</b> voting systems in wide 
use in the world today.  All voting in Louisiana, Georgia, South Carolina, New Jersey, and 
Delaware is on DREs.  Much of the voting that happens in Texas, Florida,
Tennessee, Kentucky, Indiana, Virginia, and Pennsylvania is on DREs.  Good luck
trusting the results of elections in all of these states!</p>

<p><b>There is no good reason to use DREs today.</b></p>
>>
