dre_with_vvpat() ::= <<
<p><b>That's a pretty poor choice!</b></p>

<p>You are voting with a voting system designed in the 20th century,
but unable to withstand the security threats of the 21st century.
You have put your election in the hands of state-level adversaries
like Russia, China, and North Korea, or in the hands of untrustworthy
elections officials or other political parties.</p>

<p>You use an antique computer that no longer gets updates or security patches,
created by a voting company you have never heard of, running a proprietary 
system that no one has ever seriously examined, to collect votes
and announce the election's results.</p>

<p>Fortunately, there is a paper ballot record in the form of a 
"Voter-Verifiable Paper Audit Trail", or VVPAT for short.  This means that a 
little slip of
paper is printed with your vote on it.  It is behind a piece of dirty glass, 
and is very hard to read and understand.  Consequently, voters rarely actually
look at what was printed.</p>

<p>Shockingly, even in close elections, or in elections where something fishy
has happened, election authorities very, very rarely ever look at  
VVPATs!</p>
 
<p>Basically, you have to completely trust the election authorities, 
their technology providers, and your government to have any hope that your 
vote is recorded correctly, cast in the election, is secret, and is counted 
in the election.</p>

<p>More worrisome, you have no guarantee of your privacy or anonymity, so the 
authorities could choose to look at how you vote and make your life 
miserable if you didn't vote the "right" way.</p>

<p>Also, if something goes wrong in the election&mdash;perhaps there is a virus
on the DRE that changes the way that you voted without your noticing&mdash;
it is extremely hard for the authorities to detect and mitigate the issue or 
correct the election.  Their reluctance to look at VVPATs certainly does not help!</p>

<p>Direct-recording electronic voting machines are the <b>worst</b> voting systems in wide 
use in the world today.  All voting in Utah and Nevada is on DREs with VVPAT.  Much of the 
voting that happens in California, Idaho, Alaska, Hawaii, Wyoming, Arizona, 
Missouri, Illinois, Wisconsin, Ohio, West Virginia, and North Carolina is on 
DREs with VVPAT. Some of the voting in Kansas, Arkansas, and Mississippi is 
on DREs with VVPAT.  Good luck
trusting the results of elections in all of these states!</p>

<p><b>There is no good reason to use DREs with VVPATs today.</b></p>
>>
