hand-marked(election) ::= <<
<div align="center">
<b>$election.my_name$</b><br/>
<i>$election.my_date$</i>

<h2>Hand-Counting Hand-Marked Paper Ballots</h2>

<p><b>Great choice!</b></p>

<p>You are voting with a normal paper ballot.  You get to hand-mark that
ballot with a pencil or pen, and drop the ballot into a secure ballot box.</p>

<p>This voting system is the most secure voting system in use in the world 
today.  Its operation and security threats are well-understood because people 
have been voting this way for centuries.  It also needs no technology.</p>

<p>The drawbacks of voting on paper and hand-counting is that counting by
hand requires many people and takes time.  A hundred volunteers can count
a million ballots in about twelve hours.</p>

<p>Also, training is key.  Well-trained volunteers only make one mistake in 
every 10,000 votes.  Badly trained volunteers make one mistake every 100 
votes.</p>

</div>
>>
