hand_marked() ::= <<
<p><b>Great choice!</b></p>

<p>You are voting with a normal paper ballot.  You get to hand-mark that
ballot with a pencil or pen, and drop the ballot into a secure ballot box.</p>

<p>This voting system is the most secure voting system in use in the world 
today.  Its operation and security threats are well-understood because people 
have been voting this way for centuries.  It needs no modern technology.</p>

<p>The drawbacks of voting on paper and hand-counting is that counting by
hand requires many people and takes time.  A hundred volunteers can count
a million ballots in about twelve hours. And that's for an election 
with just one race.</p>

<p>Also, training is key.  Well-trained volunteers only make one mistake 
every 10,000 votes.  Badly trained volunteers make one mistake every 100 
votes.</p>

<p>Another drawback of hand-marked paper ballots is that election officials have
to print enough ballots before the election for all voters, and have to
make printed ballots available in all of the different spoken languages used in
a jurisdiction.  It is not unusual for tens of thousands of ballots to be 
recycled after each election!</p>

<p>Finally, because the ballots are not checked for mistakes (such as voting for too
many candidates in a race) then voters who mismarked a ballot won't be warned of their mistakes.</p>

<p><b>When paper ballots are feasible, they are a secure, transparent, reliable way to conduct an election.</b></p>
>>
