internet_election() ::= <<
<h2>Internet Voting</h2>

<p><b>Terrible choice!</b></p>

<p>You are voting with a voting system designed in the 20st century,
but which unable to withstand the security threats of the 21st century.
You have put your election in the hands of state-level adversaries
like the Russia, China, and North Korea.</p>

<p>You use a computer to mark up and submit a digital ballot.  The election
authorities, or some internet voting company you have never heard of,
run a proprietary system that no one has ever examined to collect votes
and announce the election's results.</p>

<p>Unfortunately, there is no paper ballot record and no guaranteed receipt of 
your voting.  Also, you have to completely trust the election authorities, 
their technology providers, and your government to have any hope that your 
vote is recorded correctly, cast in the election, is secret, and is counted 
in the election.</p>

<p>More worrisome, you have no guarantee of your privacy or anonymity, so the 
authorities of could choose to look at how you vote and make your life 
miserable if you didn't vote the "right" way.</p>

<p>Also, if something goes wrong in the election---say that there is a virus
on your computer that changes the way that you voted without your noticing---
there is no way for the authorities to detect, mitigate, and 
correct the election.</p>

<p>This voting system is the <b>least</b> secure voting system in use in the world 
today.  This kind of voting system has been experimented with and rejected by
numerous governments around the world, but is being used in around two dozen
states in the U.S.A. to collect votes from overseas Americans and military 
personnel.</p>

<p><b>There is no good reason to use internet voting today.</b></p>
>>
