internet_election() ::= <<
<p><b>Terrible choice of voting system!</b></p>

<p>You are voting with a voting system designed in the 20th century,
but unable to withstand the security threats of the 21st century.
</p>

<p>You use a computer or a smartphone to mark up and submit a digital ballot.  
The election authority, or some Internet voting company you have probably never heard of,
runs a proprietary system to collect votes
and announce the election's results.</p>

<p>Unfortunately, there is no paper record of 
your vote.  You have to trust the election authorities and 
their technology providers to have any hope that your 
vote is recorded correctly, remains secret, and is counted in the election.</p>

<p>You have put your vote within the reach of sophisticated hackers like state-level adversaries
like Russia, China, and North Korea.</p>

<p>You have no guarantee of your privacy or anonymity, so the 
authorities could choose to look at how you vote and make your life 
miserable if you didn't vote the "right" way.</p>

<p>Also, if something goes wrong in the election&mdash;perhaps there is a virus
on your computer that changes the way that you voted without your noticing&mdash;
there is no way for the authorities to detect and mitigate the issue or 
correct the election.</p>

<p><b>Internet voting is the <em>least secure</em> type of voting system in use in the world 
today. </b></p>
>>
