landing(election) ::= <<
<div align="center">
<h2>$election.name$ &ndash; $election.date$</h2>
<h3>$election.description$</h3>
<h2><a href="/voting_system_choice">Vote!</a>&nbsp;&nbsp;&nbsp;<a href="/adversary">Hack!</a></h2>

<p>$election.voteCount$ votes have been cast in this election. $election.voteManipulationCount$ votes and 
$election.receiptManipulationCount$ records have been hacked.</p>
</div>
>>
