optical_scan() ::= <<
<p><b>Very good choice of voting system!</b></p>

<p>You are voting with the dominant voting system deployed in the U.S.A. today.
To vote in an optical scan system, you mark a paper ballot. 
You then drop the ballot into a normal secure ballot box, or
you put the ballot into a precinct scanner which double-checks that you filled 
out the ballot correctly.</p>

<p>When it is time to count the votes in this kind of election, 
a computer scans and interprets the marks on the ballots, voting 
officials review the computer's interpretations, and a computer tallies the 
results.</p>

<p>This voting system is a fairly reliable, though complicated, choice.  Its 
operation and security threats are fairly well understood because people 
have been voting on paper for centuries.  Moreover, since voting and scanning 
are decoupled, voter privacy and anonymity is well-preserved.</p>

<p>There are a few drawbacks to voting with optical scan devices.  They are 
traditionally fairly expensive, run on old hardware and software that does 
not see upgrades or security patches, and scanning takes a lot of time.</p>

<p>On the positive side though, if a precinct scanner is used, all votes will 
be well-formed and can be counted, so no voters are accidentally 
disenfranchised.  Moreover, there is a paper ballot record that can always be
used in recounts or audits of close or contested elections.</p>

<p> All voting in Montana, North and South Dakota, Nebraska, 
New Mexico, Oklahoma, Iowa, Minnesota, Michigan, New York, Alabama, Maryland,
Maine, New Hampshire, Vermont, Connecticut, Rhode Island, Maryland, and 
Washington D.C. uses optical scan systems.</p>

<p>Finally, not only do voters in Washington,
Colorado, and Oregon use optical scan systems, but they also get to vote by 
mail.  Voters in these states receive their ballots in the mail weeks before an
election, can vote from home when and how they wish, and drop off their ballots
in a secure ballot drop or put them in the mail.  Unfortunately, this means that
elections officials cannot guarantee that each vote was filled out by exactly
the right voter, nor can we be sure that voters were not coerced and did not sell their
votes to the highest bidder.</p>

<p> This voting system is the <em>best</em> voting system widely deployed in the
U.S.A. today. </p> 
>>
