verifiable-election() ::= <<
<h2>End-to-End Verifiable Election</h2>

<p><b>Great choice!</b></p>

<p>You are voting with a voting system of the 21st century.  You make a ballot
using a ballot marking device.  That device produces a normal paper ballot as 
well as a receipt.
You drop the ballot into a secure ballot box and, after the election is over,
you can use the receipt to check that your vote was included in the final
election tally.  Moreover, you cannot prove to anyone how you voted.</p>

<p>This voting system will be the most secure voting system in use in the world 
in the coming years.  This kind of voting system has been experimented with 
around the world, and is a hot topic of research in academia and industry.</p>

<p>There are several good reasons to use verifiable elections technology. 
Ballot marking devices guarantee that your ballot is completed correctly. They
also can show ballots and instructions in any language---a very useful feature
in some larger U.S. jurisdictions which must support nearly two dozen 
languages!  Counting the votes also just takes a few minutes and is always
correct.</p>

<p>The fact that there is a paper ballot that voters can see, read, and 
understand is critical.  Moreover, authorities can always return to the paper
record if there is a recount or audit.  

<p>Finally, many of these systems have advanced auditing features built in that 
can help authorities check on the integrity and accuracy of the election 
quickly and inexpensively.</p>

<p>The drawbacks of voting using verifiable elections technology is that the
cost of the election can be high.  Basically, every voter has to use a 
computer with a touch-screen and a printer, both of which can be expensive 
devices.  Also, many voters are unfamiliar or uncomfortable with technology---
not everyone has a smartphone or tablet computer after all!</p>  

<p>Finally, having
to rely upon the fancy cryptography which is necessary, behind the scenes,
to provide all of these 21st century features makes many uncomfortable.  After 
all, now it is no longer the case that any voter can come to understand how an
election works.  In fact, very few have the background to understand and vet
the necessary cryptography and advanced computer science necessary to realize
verifiable elections!</p>

>>
