verifiable_election() ::= <<
<p><b>Great choice!</b></p>

<p>You are voting with a voting system of the 21st century.  You make a ballot
using a ballot marking device.  That device produces a normal paper ballot as 
well as a receipt with a coded record of your choices.
You drop the ballot into a secure ballot box. After the election is over,
you can use the receipt to check that your vote was included in the final
election tally.  But because the receipt is coded, you cannot prove to anyone how you voted.</p>

<p>This voting system will be the most secure voting system in use in the world 
in the coming years.  It is a hot topic of research in academia and industry.</p>

<p>There are several good reasons to use verifiable elections technology. 
Ballot marking devices guarantee that your ballot is completed correctly. They
can also show ballots and instructions in any language&mdash;a very useful feature
in some larger U.S. jurisdictions that must support nearly two dozen 
languages!  Counting the votes takes just a few minutes.</p>

<p>The fact that there is a paper ballot that voters can see, read, and 
understand is critical.  Moreover, authorities can always return to the paper
record if there is a recount or audit.</p>

<p>Finally, many of these systems have advanced auditing features built in that 
can help authorities quickly and inexpensively check on the integrity and 
accuracy of the election.</p>

<p>Having
to rely upon the fancy cryptography that is necessary, behind the scenes,
to provide all of these 21st century features makes many uncomfortable.  In 
such a system,  it is no longer the case that any voter can come to understand 
exactly how an election works.  But political parties and watchdog groups can organize 
independently to check that votes are recorded and counted as cast.</p>

<p><b>End-to-end verifiable election systems promise to be </em>the most secure</em>.</b></p>
>>
